  query subscriptions($appId: String!, $states: [State!], $artifactIds: ArtifactIdInput!) {
  subscriptions(appId: $appId,states: $states,artifactIds: $artifactIds) {
    appId,
    userId,
    role,
    state,
    artifact {
      elements {
        artifactIdElement {
          id
        }
        title
      }
        },
    channelSettings {
      email {
        frequency
      },
      mobilePush {
        frequency
      }
    }
  }
}