mutation unsubscribe($subscriptionId: SubscriptionIdInput!) {
  unsubscribe(subscriptionId: $subscriptionId) {
    appId
    artifactId {
      elements {
        id
      }
    }
    userId
    state
  }
}

